mtblog/config/routes.rb
Rails.application.routes.draw do
  get 'signups/index'
  resources :signups do
  resources :comments
end

  root 'signups#index'

end

mtblog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

mtblog/app/models/signup.rb
class Signup < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true,
  length: { minimum: 5 }
end

mtblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

mtblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "nrc", password: "secret", only: :destroy

  def create
    @signup = Signup.find(params[:signup_id])
    @comment = @signup.comments.create(comment_params)
    redirect_to article_path(@signup)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

mtblog/app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :set_signup, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "nrc", password: "secret", except: [:index, :show]

  # GET /signups
  # GET /signups.json
  def index
    @signups = Signup.all
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
  end

  # GET /signups/new
  def new
    @signup = Signup.new
  end

  # GET /signups/1/edit
  def edit
  end

  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(signup_params)

    respond_to do |format|
      if @signup.save
        format.html { redirect_to @signup, notice: 'Signup was successfully created.' }
        format.json { render :show, status: :created, location: @signup }
      else
        format.html { render :new }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signups/1
  # PATCH/PUT /signups/1.json
  def update
    respond_to do |format|
      if @signup.update(signup_params)
        format.html { redirect_to @signup, notice: 'Signup was successfully updated.' }
        format.json { render :show, status: :ok, location: @signup }
      else
        format.html { render :edit }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup.destroy
    respond_to do |format|
      format.html { redirect_to signups_url, notice: 'Signup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signup
      @signup = Signup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signup_params
      params.require(:signup).permit(:FisrtName, :LastName, :Email)
    end
end

mtblog/app/helpers/application_helper.rb
module ApplicationHelper
end

mtblog/app/helpers/comments_helper.rb
module CommentsHelper
end

mtblog/app/helpers/signups_helper.rb
module SignupsHelper
end

mtblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mtblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

mtblog/app/views/signups/_form.html.erb
<%= form_for(@signup) do |f| %>
  <% if @signup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signup.errors.count, "error") %> prohibited this signup from being saved:</h2>

      <ul>
      <% @signup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :FisrtName %><br>
    <%= f.text_field :FisrtName %>
  </div>
  <div class="field">
    <%= f.label :LastName %><br>
    <%= f.text_field :LastName %>
  </div>
  <div class="field">
    <%= f.label :Email %><br>
    <%= f.text_field :Email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mtblog/app/views/signups/edit.html.erb
<h1>Editing signup</h1>

<%= render 'form' %>

<%= link_to 'Show', @signup %> |
<%= link_to 'Back', signups_path %>

mtblog/app/views/signups/index.html.erb
<h1>Listing signups</h1>

<table>
  <thead>
    <tr>
      <th>Fisrtname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @signups.each do |signup| %>
      <tr>
        <td><%= signup.FisrtName %></td>
        <td><%= signup.LastName %></td>
        <td><%= signup.Email %></td>
        <td><%= link_to 'Show', signup %></td>
        <td><%= link_to 'Edit', edit_signup_path(signup) %></td>
        <td><%= link_to 'Destroy', signup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Signup', new_signup_path %>

mtblog/app/views/signups/new.html.erb
<h1>New signup</h1>

<%= render 'form' %>

<%= link_to 'Back', signups_path %>

mtblog/app/views/signups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fisrtname:</strong>
  <%= @signup.FisrtName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @signup.LastName %>
</p>

<p>
  <strong>Email:</strong>
  <%= @signup.Email %>
</p>

<h2>Comments</h2>
<% @signup.comments.each do |comment| %>
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@signup, @signup.comments.build]) do |f| %>
<p>
  <%= f.label :commenter %><br>
  <%= f.text_field :commenter %>
</p>
<p>
  <%= f.label :body %><br>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>




<%= link_to 'Edit', edit_signup_path(@signup) %> |
<%= link_to 'Back', signups_path %>